// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data;

namespace LibraryBackend.Models
{
    public partial class User
    {
        public User()
        {
        }

        public int Id { get; set; }

        [Required]
        public string FirstName { get; set; }
        [Required]
        public string Lastname { get; set; }
        [EmailAddress]
        public string Email { get; set; }
        [MinLength(4)]
        [MaxLength(255)]
        public byte[] PasswordHash { get; set; }
        [Required]
        public int RoleId { get; set; }
    }
}